# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
