# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0004_remove_school_info_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img_schoolmessage/'),
        ),
    ]
