# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0005_school_info_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_info',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
