# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0009_auto_20170923_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='school_info',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
