# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0010_auto_20170924_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_info',
            name='picture',
            field=models.ImageField(upload_to='img/%Y/%m/%d/'),
        ),
    ]
