# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yhbot', '0011_auto_20170924_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_info',
            old_name='picture',
            new_name='img',
        ),
    ]
